import { Paystack } from "paystack-sdk";

let paystackClient: Paystack | null = null;

/**
 * Retrieves the singleton instance of the Paystack client.
 *
 * If the client has not been initialized yet, this function creates a new instance
 * using the Paystack secret key from the runtime configuration.
 *
 * @returns {Paystack} The initialized Paystack client instance.
 */
export function getPaystackClient(): Paystack {
  if (!paystackClient) {
    const config = useRuntimeConfig();
    paystackClient = new Paystack(config.paystackSecretKey);
  }
  return paystackClient;
}

/**
 * Initializes a transaction with Paystack.
 *
 * This function prepares a payment request by interacting with the Paystack API. It handles
 * currency conversion (multiplying amount by 100 for kobo/pesewas), sets default channels,
 * and passes the necessary metadata and callback URL.
 *
 * @param params - The configuration object for initializing the transaction.
 * @param params.email - The email address of the customer making the payment.
 * @param params.amount - The transaction amount in the base currency unit (e.g., GHS, NGN).
 *                        This value is automatically multiplied by 100 to convert to
 *                        the smallest currency unit (e.g., pesewas) before sending to Paystack.
 * @param params.reference - A unique string to identify this specific transaction.
 * @param params.currency - The currency code for the transaction (default: "GHS").
 * @param params.metadata - Optional key-value pairs to store additional data about the transaction.
 * @param params.channels - An optional array of payment channels to make available
 *                          (e.g., "card", "mobile_money"). Defaults to all major channels.
 * @param params.callbackUrl - The URL to redirect the user to after payment is attempted.
 *
 * @returns A promise that resolves to the Paystack initialization response, containing the authorization URL and access code.
 */
export async function initializePaystackTransaction(
  params: {
    email: string;
    amount: number;
    reference: string;
    currency?: string;
    metadata?: Record<string, string | number | boolean | object | []>;
    channels?: string[];
    callbackUrl?: string;
  },
) {
  const paystack = getPaystackClient();

  return await paystack.transaction.initialize({
    email: params.email,
    amount: Math.ceil(params.amount * 100).toString(),
    reference: params.reference,
    currency: params.currency || "GHS",
    metadata: params.metadata,
    channels: params.channels || ["card", "bank", "ussd", "qr", "mobile_money", "bank_transfer"],
    callback_url: params.callbackUrl,
  });
}

/**
 * Verifies a transaction using the Paystack API given a transaction reference.
 *
 * @param reference - The unique transaction reference string generated by Paystack during initialization.
 * @returns A promise that resolves to the verification details of the transaction from Paystack.
 */
export async function verifyPaystackTransaction(reference: string) {
  const paystack = getPaystackClient();
  return await paystack.transaction.verify(reference);
}
